version: "3.7"

networks:
  red:
    external: true
  
services: 
  ventas:
    image: santiago840/ventas:3.0
    restart: always
    ports:
      - 8080:8080
    environment:
      - MYSQL_HOST=db
    expose:
      - "8080"
    networks:
      - red
    links:
      - db
    depends_on:
      - db

  libros:
    image: santiago840/libros:1.0
    restart: always
    ports:
      - 8081:8080
    environment:
      - MYSQL_HOST=db
    expose:
      - "8080"
    networks:
      - red
    links:
      - db
    depends_on:
      - db

  db:
    image: santiago840/ventasbd:1.0
    restart: always
    environment:
      - MYSQL_DATABASE=tienda
      - MYSQL_USER=yo
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3306:3306"
    expose:
      - "3306"
    networks:
      - red
    volumes:
      - mi-volumencito:/var/lib/mysql
volumes:
  mi-volumencito:
    
    
